swagger: '2.0'

# basic meta information
info:
  title: flow-id-example
  version: '1.0'
  description: Very nice flow-id-example

externalDocs:
  description: External docs
  url: http://example.github.io/

# technical configuration
basePath: /
produces:
- application/json
consumes:
- application/json

paths:

  '/':
    get:
      summary: Application root
      operationId: org.zalando.stups.friboo.system.http/redirect-to-swagger-ui
      responses:
        default:
          description: "Redirects to /ui/"
  '/exists/{status}':
    get:
      summary: Get http status
      parameters:
        - $ref: '#/parameters/Status'
        - $ref: '#/parameters/FlowId'
      operationId: "example.flow-id-example.api/get-status"
      responses:
        200:
          description: It works!
        default:
          $ref: '#/responses/Error'
  '/exists-with-fid-component/{status}':
    get:
      summary: Get http status
      parameters:
        - $ref: '#/parameters/Status'
        - $ref: '#/parameters/FlowId'
      operationId: "example.flow-id-example.api/get-status-with-flow-id-component"
      responses:
        200:
          description: It works!
        default:
          $ref: '#/responses/Error'

parameters:
  Status:
    name: status
    in: path
    type: integer
    description: HTTP status code to check
  FlowId:
    name: x-flow-id
    in: header
    type: string
    description: Flow tracking header to be passed to dependency calls

responses:
  Error:
    description: An error occured.
    schema:
      $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      message:
        type: string
    example:
      message: Internal Server Error
